import Head from "next/head";
import { Inter } from "next/font/google";
import Banner from "~/components/Banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Test Slider</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`${inter.className} container`}>
        <Banner />
      </div>
    </>
  );
}
